{"name": "Проверка ошибки при создания курьера с уже существующим логином", "status": "broken", "statusDetails": {"message": "TypeError: 'list' object is not callable", "trace": "self = <test_courier_registration.TestCourierRegistration object at 0x000002070FD90B60>\ncreate_courier_stable = ['ninja030624', '1234', 'saske']\n\n    @allure.title('Проверка ошибки при создания курьера с уже существующим логином')\n    def test_courier_registration_double_login(self, create_courier_stable):\n>       courier = create_courier_stable()\nE       TypeError: 'list' object is not callable\n\ntests\\test_courier_registration.py:16: TypeError"}, "start": 1717797964744, "stop": 1717797964745, "uuid": "d1dabe9f-1abc-4191-8006-b2f98cde1bd6", "historyId": "52366e9ffddfc75ce2621a3c2548bc68", "testCaseId": "52366e9ffddfc75ce2621a3c2548bc68", "fullName": "tests.test_courier_registration.TestCourierRegistration#test_courier_registration_double_login", "labels": [{"name": "feature", "value": "Проверка ручки регистрация курьера"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_registration"}, {"name": "subSuite", "value": "TestCourierRegistration"}, {"name": "host", "value": "DESKTOP-9ENBRFN"}, {"name": "thread", "value": "29484-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_registration"}]}